### ISSUE TITLE
网站导航栏链接的问题

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/discourse#4]
1. 现在有 Book 和 Github 两个链接，假设我先点了 Book，之后再点 Github 的话，Github 的页面会直接在 Book 的 Tab 显示。我第一次见这样的链接，难免有些惊讶。并且，我不确定是不是值得这么做。
2. Github 的链接是：https://github.com/emacs-china ，不是 http://www.github.com/emacs-china ，虽然后者会被重定向至前者。
3. 我觉得直接用一个 About 页面。目前的 Book 和 Github，不点开就不知道到底是什么。

**Comment by zilongshanren** [comment]
@xuchunyang   感谢反馈，我去修复一下链接和跳转的问题。
至于 book 和 github 页面，我觉得还可以再讨论一下，到底是用一个 About 页面，还是目前这样。
另外，About 页面里的内容该怎么定？是否可以考虑用之前我做的那个 Single Page 当作主页？

**Comment by zilongshanren** [comment]
@xuchunyang 
你提到的前面两个问题已经修复了。
第三个问题，我觉得可以再讨论一下。

**Comment by xuchunyang** [comment]
如果论坛确认作为主页了，我觉得用一个 About 页面比较合适，并在论坛的导航栏上放个链接。导航栏位置毕竟有限，尽量放些常用或者必不可少的东西。

> 另外，About 页面里的内容该怎么定？是否可以考虑用之前我做的那个 Single Page 当作主页？

我觉得可以，既然已经做了，为什么不呢！

**Comment by zilongshanren** [comment]
@xuchunyang 
恩，回头再跟大家讨论一下。Book, Github, About 这三个都放也可以吧？
Book 要么重命名一下，改成 Mastering Emacs in 21 Days...
虽然名字有点长。。

**Comment by xuchunyang** [comment]
> Book, Github, About 这三个都放也可以吧？

可以，只要大家觉得值得的话。我觉得只放常用、重要或必要的链接比较合适，另外这些链接的描述应该尽量清楚。

**Comment by xuchunyang** [comment]
看[这个帖子](http://forum.emacs-china.org/t/org-mode/140/5)的时候发现一个问题：（标题和新加的链接重叠了）

![screen shot 2016-04-27 at 21 05 37](https://cloud.githubusercontent.com/assets/4550353/14852959/fd086ad0-0cbb-11e6-8525-29977327c594.png)

**Comment by zilongshanren** [comment]
@xuchunyang  我觉得应该要限制一个标题的最大长度。。。

**Comment by qinshulei** [comment]
我觉得这应该是人家的设计，我们把链接放在这个位置，会和人家的设计矛盾，要修正会涉及比较多的地方．

我觉得我们可以考虑把链接放在其他地方，比如单独的一个panel.像v2ex那样,但可能和discourse的刷新功能矛盾，只能放在论坛上面:
![example1](https://cloud.githubusercontent.com/assets/2012618/14873864/49c7fc3e-0d2d-11e6-8a0e-c397f787e0b5.png)

或者是放在这个里面，这个里面本来就放置了比较多的链接，符合它本身的设计:
![example2](https://cloud.githubusercontent.com/assets/2012618/14873865/4a126094-0d2d-11e6-85f9-5da9339a5cbb.png)

**Comment by xuchunyang** [comment]
> @xuchunyang 我觉得应该要限制一个标题的最大长度。。。

其实已经限制了（最后面的三个点），Github 的链接就一直没有被挡住。进一步减少最大长度，会令标题更加难读。只放一个链接应该没问题。

> 我觉得我们可以考虑把链接放在其他地方，比如单独的一个panel.像v2ex那样,但可能和discourse的刷新功能矛盾，只能放在论坛上面:

同意放在最上面。

这是官方的示例论坛（ http://try.discourse.org/ ），最上面也有个导航栏，一往下滚动，就会被隐藏，对论坛的干扰要小很多。这里（ http://ask.githuber.cn/ ）还有一个例子。

> 或者是放在这个里面，这个里面本来就放置了比较多的链接，符合它本身的设计:

不同意。虽然这里的内容都是链接，但都是与论坛本身密切相关的，而我们要加的链接跟论坛本身不相关。

**Comment by zilongshanren** [comment]
@xuchunyang  要不暂时只放一个 About 链接吧。

或者像  http://ask.githuber.cn/  一样，链接放在论坛 logo 的上面。

**Comment by zilongshanren** [comment]
@xuchunyang 
现在修改了一下，你看看如何。

**Comment by xuchunyang** [comment]
> 要不暂时只放一个 About 链接吧。

可以

> 或者像 http://ask.githuber.cn/ 一样，链接放在论坛 logo 的上面。

更好（尤其是在要放多个链接的时候）。http://try.discourse.org/ 的导航栏看起来更漂亮

> 现在修改了一下，你看看如何。

http://try.discourse.org/  和  http://ask.githuber.cn/  中的导航栏不是固定的，一旦向下滚动的时候，就会被隐藏起来，我觉得这样更好。

**Comment by qinshulei** [comment]
@xuchunyang @zilongshanren 

我看了一下　http://try.discourse.org/ 的效果，是直接　admin/customize　里面弄得，代码也都是明的．
修改admin/customize里面的html和css就行了．修改如下，链接和图片需要调整：

http://forum.emacs-china.org/admin/customize/css_html/1/header

``` html
<nav id="bar">
  <div>
    <a class="nav-link" href="http://www.discourse.org">
      <img width="64" height="45" src="http://www.discourse.org/images/nav-icon-gray.png" alt="logo">
    </a>
    <a class="nav-link red" href="http://www.discourse.org/about/">About</a>
    <a class="nav-link orange" href="http://www.discourse.org/faq/">FAQ</a>
    <a class="nav-link yellow" href="http://blog.discourse.org">Blog</a>
    <a class="nav-link green selected" href="http://try.discourse.org">Try It</a>
    <a class="nav-link blue" href="http://www.discourse.org/buy">Buy It</a>
    <a class="nav-link grey" href="http://meta.discourse.org">Meta</a>
    <a class="fork-us" href="http://github.com/discourse/discourse"><i class="icon-github-alt"></i>&nbsp;Fork Us</a>
  </div>
</nav>
```

http://forum.emacs-china.org/admin/customize/css_html/1/css

``` css
#main-outlet {
  margin-top: 48px;
  padding-top: 75px; }

body .d-header #site-logo {
  height: 40px;
  max-width: 251px; }

.docked #main-outlet {
  margin-top: 0;
  padding-top: 123px; }

.docked nav#bar {
  display: none; }

nav#bar {
  width: 100%;
  height: 48px;
  background: #1b1f20;
  position: absolute;
  top: 0;
  z-index: 1; }

nav#bar div {
  width: 765px;
  margin: 0px auto; }

nav#bar a.nav-link {
  color: #FFF;
  text-decoration: none;
  text-align: center;
  -webkit-text-stroke: 0.2px;
  font-family: 'Montserrat', sans-serif; }

nav#bar a.nav-link {
  line-height: 48px;
  min-width: 90px;
  text-align: center;
  font-size: 16px;
  float: left; }

nav#bar a.red.selected {
  color: #d13332;
  border-color: #d13332 !important; }

nav#bar a.red:hover {
  color: #d13332;
  text-shadow: 0px 0px 5px #d13332; }

nav#bar a.orange.selected {
  color: #ea5932;
  border-color: #ea5932 !important; }

nav#bar a.orange:hover {
  color: #ea5932;
  text-shadow: 0px 0px 5px #ea5932; }

nav#bar a.yellow.selected {
  color: #fff9ae;
  border-color: #fff9ae !important; }

nav#bar a.yellow:hover {
  color: #fff9ae;
  text-shadow: 0px 0px 5px #fff9ae; }

nav#bar a.green.selected {
  color: #18b159;
  border-color: #18b159 !important; }

nav#bar a.green:hover {
  color: #18b159;
  text-shadow: 0px 0px 5px #18b159; }

nav#bar a.blue.selected {
  color: #00aeef;
  border-color: #00aeef !important; }

nav#bar a.blue:hover {
  color: #00aeef;
  text-shadow: 0px 0px 5px #00aeef; }

nav#bar a.grey.selected {
  color: #aaa;
  border-color: #aaa !important; }

nav#bar a.grey:hover {
  color: #aaa;
  text-shadow: 0px 0px 5px #aaa; }

nav#bar a.nav-link.selected {
  line-height: 42px;
  border-top: 3px solid #0b0d0d;
  background-color: #0b0d0d;
  height: 45px; }

nav#bar a.fork-us {
  float: right;
  border-radius: 4px;
  background-color: #2b3234;
  width: 104px;
  height: 32px;
  line-height: 32px;
  margin-top: 8px;
  font-weight: bold;
  font-size: 14px;
  text-decoration: none;
  color: #FFF;
  text-align: center;
  font-family: sans-serif; }

nav#bar a.fork-us:hover {
  background-color: #434748; }

nav#bar a.fork-us:active {
  background-color: #000; }
```
